import { Store, StoreCategory, StoreItem, OrderSession, MenuSnapshot, MenuSnapshotItem, MemberOrder } from '../types';

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-mcd',
    name: "McDonald's",
    description: 'Burgers, French Fries, Fried Chicken & Beverages',
    logo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=150&auto=format&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&auto=format&fit=crop&q=80',
    address: 'Grand Indonesia, West Mall Lower Ground, Jakarta',
    phone: '14045',
    website: 'https://mcdonalds.co.id',
    status: 'active',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'store-kfc',
    name: 'KFC (Kentucky Fried Chicken)',
    description: 'Crispy Fried Chicken, Burgers, & Colonel Combo Meals',
    logo: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=150&auto=format&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    address: 'Sudirman Central Business District, Jakarta',
    phone: '14022',
    website: 'https://kfcku.com',
    status: 'active',
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'store-kopi-kenangan',
    name: 'Kopi Kenangan',
    description: 'Kopi Kenangan Mantan, Toast & Freshly Brewed Coffee',
    logo: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=150&auto=format&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
    address: 'Pacific Place Mall Lt. 3, Jakarta',
    phone: '0811123456',
    website: 'https://kopikenangan.com',
    status: 'active',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'store-sederhana',
    name: 'Restoran Sederhana Nasi Padang',
    description: 'Authentic West Sumatran Rendang, Ayam Pop, & Sambal Hijau',
    logo: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=150&auto=format&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=80',
    address: 'Jl. Sabang No. 34, Central Jakarta',
    phone: '021-3151234',
    website: 'https://restoransederhana.id',
    status: 'active',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const INITIAL_CATEGORIES: StoreCategory[] = [
  // McDonald's
  { id: 'mcd-cat-1', store_id: 'store-mcd', name: 'Burgers', sort_order: 1 },
  { id: 'mcd-cat-2', store_id: 'store-mcd', name: 'Chicken & Fish', sort_order: 2 },
  { id: 'mcd-cat-3', store_id: 'store-mcd', name: 'Snacks & Sides', sort_order: 3 },
  { id: 'mcd-cat-4', store_id: 'store-mcd', name: 'Drinks & Desserts', sort_order: 4 },

  // KFC
  { id: 'kfc-cat-1', store_id: 'store-kfc', name: 'Combo Meals', sort_order: 1 },
  { id: 'kfc-cat-2', store_id: 'store-kfc', name: 'Ala Carte Chicken', sort_order: 2 },
  { id: 'kfc-cat-3', store_id: 'store-kfc', name: 'Sides & Drinks', sort_order: 3 },

  // Kopi Kenangan
  { id: 'kk-cat-1', store_id: 'store-kopi-kenangan', name: 'Espresso & Milk Coffee', sort_order: 1 },
  { id: 'kk-cat-2', store_id: 'store-kopi-kenangan', name: 'Non-Coffee', sort_order: 2 },
  { id: 'kk-cat-3', store_id: 'store-kopi-kenangan', name: 'Soft Baked Cookies & Toast', sort_order: 3 },

  // Sederhana
  { id: 'sed-cat-1', store_id: 'store-sederhana', name: 'Lauk Utama (Main Dishes)', sort_order: 1 },
  { id: 'sed-cat-2', store_id: 'store-sederhana', name: 'Paket Nasi Box', sort_order: 2 },
  { id: 'sed-cat-3', store_id: 'store-sederhana', name: 'Minuman (Drinks)', sort_order: 3 },
];

export const INITIAL_ITEMS: StoreItem[] = [
  // McDonald's Items
  {
    id: 'mcd-item-1',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-1',
    name: 'Big Mac',
    description: 'Two 100% beef patties with special Big Mac sauce, lettuce, cheese, pickles & onions on a sesame seed bun.',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-2',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-1',
    name: 'McChicken',
    description: 'Crispy chicken patty topped with mayonnaise and shredded lettuce on a toasted bun.',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1615297928064-24977384d0da?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-3',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-1',
    name: 'Double Cheeseburger',
    description: 'Two 100% beef patties with two slices of melted cheese, pickles, onions, ketchup, and mustard.',
    price: 42000,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-4',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-2',
    name: 'Ayam McD Spicy (2 Pcs)',
    description: 'Signature crispy spicy fried chicken pieces marinated with secret spices.',
    price: 42500,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-5',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-3',
    name: 'French Fries (Large)',
    description: 'Crispy golden fries lightly salted to perfection.',
    price: 26000,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-6',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-3',
    name: 'McNuggets (6 Pcs)',
    description: '6 pieces of tender white meat chicken nuggets served with Sweet & Sour sauce.',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-7',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-4',
    name: 'Coca-Cola (Large)',
    description: 'Refreshing ice cold Coca-Cola soft drink.',
    price: 18000,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mcd-item-8',
    store_id: 'store-mcd',
    category_id: 'mcd-cat-4',
    name: 'McFlurry Oreo',
    description: 'Creamy soft serve ice cream blended with crushed Oreo cookie pieces.',
    price: 16500,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // KFC Items
  {
    id: 'kfc-item-1',
    store_id: 'store-kfc',
    category_id: 'kfc-cat-1',
    name: 'Super Besar 1',
    description: '1 Piece Crispy Chicken + 1 Rice + 1 Medium Coca-Cola',
    price: 38500,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kfc-item-2',
    store_id: 'store-kfc',
    category_id: 'kfc-cat-1',
    name: 'Super Besar 2',
    description: '2 Pieces Crispy Chicken + 1 Rice + 1 Medium Coca-Cola',
    price: 54000,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kfc-item-3',
    store_id: 'store-kfc',
    category_id: 'kfc-cat-2',
    name: 'Zinger Burger',
    description: 'Juicy crunchy chicken thigh fillet with spicy mayo and fresh lettuce.',
    price: 41000,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Kopi Kenangan
  {
    id: 'kk-item-1',
    store_id: 'store-kopi-kenangan',
    category_id: 'kk-cat-1',
    name: 'Kopi Kenangan Mantan (Large)',
    description: 'Signature espresso with fresh milk and authentic organic palm sugar (Gula Aren).',
    price: 24000,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kk-item-2',
    store_id: 'store-kopi-kenangan',
    category_id: 'kk-cat-1',
    name: 'Americano (Ice)',
    description: 'Double shot rich espresso topped with fresh cold water.',
    price: 18000,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'kk-item-3',
    store_id: 'store-kopi-kenangan',
    category_id: 'kk-cat-3',
    name: 'Soft Cookie Choco Chip',
    description: 'Warm soft baked cookie loaded with Belgian chocolate chips.',
    price: 15000,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Sederhana Nasi Padang
  {
    id: 'sed-item-1',
    store_id: 'store-sederhana',
    category_id: 'sed-cat-1',
    name: 'Rendang Daging Sapi',
    description: 'Slow-cooked tender beef rendang in rich coconut milk and Minang spices.',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sed-item-2',
    store_id: 'store-sederhana',
    category_id: 'sed-cat-1',
    name: 'Ayam Pop',
    description: 'Traditional steamed skinless chicken cooked in coconut water, served with garlic sambal.',
    price: 28000,
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sed-item-3',
    store_id: 'store-sederhana',
    category_id: 'sed-cat-2',
    name: 'Paket Nasi Rendang Komplit',
    description: 'Nasi hangat, Rendang Daging, Daun Singkong, Sayur Nangka, Sambal Hijau & Bumbu Rendang.',
    price: 45000,
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sed-item-4',
    store_id: 'store-sederhana',
    category_id: 'sed-cat-3',
    name: 'Es Teh Manis',
    description: 'Indonesian chilled sweet jasmine tea.',
    price: 8000,
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Default demo snapshot & active session
export const DEMO_SNAPSHOT: MenuSnapshot = {
  id: 'snap-demo-mcd',
  store_id: 'store-mcd',
  store_name: "McDonald's",
  store_logo: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=150&auto=format&fit=crop&q=80',
  store_address: 'Grand Indonesia, West Mall Lower Ground, Jakarta',
  created_at: new Date().toISOString(),
};

export const DEMO_SNAPSHOT_ITEMS: MenuSnapshotItem[] = INITIAL_ITEMS.filter(
  (item) => item.store_id === 'store-mcd'
).map((item) => ({
  id: `snap-${item.id}`,
  snapshot_id: 'snap-demo-mcd',
  category_name:
    INITIAL_CATEGORIES.find((c) => c.id === item.category_id)?.name || 'General',
  name: item.name,
  description: item.description,
  price: item.price,
  image: item.image,
  is_available: item.is_available,
  original_item_id: item.id,
}));

export const DEMO_SESSION: OrderSession = {
  id: 'session-friday-lunch',
  host_id: 'host-1',
  host_name: 'Sarah (Team Lead)',
  store_id: 'store-mcd',
  menu_snapshot_id: 'snap-demo-mcd',
  name: 'Friday Office Lunch 🍔',
  share_code: 'a8F92k',
  status: 'open',
  deadline: new Date(Date.now() + 1000 * 60 * 45).toISOString(), // 45 mins from now
  shipping_cost: 20000,
  shipping_split_method: 'equal',
  payment_notes: 'Please transfer to BCA 8830129482 a.n. Sarah or GoPay 08123456789',
  created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_ORDERS: MemberOrder[] = [
  {
    id: 'order-afif',
    session_id: 'session-friday-lunch',
    member_id: 'member-afif',
    member_name: 'Afif',
    items: [
      {
        id: 'oi-1',
        order_id: 'order-afif',
        snapshot_item_id: 'snap-mcd-item-1',
        item_name: 'Big Mac',
        unit_price: 45000,
        quantity: 1,
        notes: 'No pickles please',
        subtotal: 45000,
      },
      {
        id: 'oi-2',
        order_id: 'order-afif',
        snapshot_item_id: 'snap-mcd-item-5',
        item_name: 'French Fries (Large)',
        unit_price: 26000,
        quantity: 1,
        subtotal: 26000,
      },
    ],
    food_subtotal: 71000,
    shipping_share: 5000,
    grand_total: 76000,
    payment_status: 'paid',
    status: 'submitted',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'order-budi',
    session_id: 'session-friday-lunch',
    member_id: 'member-budi',
    member_name: 'Budi',
    items: [
      {
        id: 'oi-3',
        order_id: 'order-budi',
        snapshot_item_id: 'snap-mcd-item-4',
        item_name: 'Ayam McD Spicy (2 Pcs)',
        unit_price: 42500,
        quantity: 1,
        subtotal: 42500,
      },
      {
        id: 'oi-4',
        order_id: 'order-budi',
        snapshot_item_id: 'snap-mcd-item-7',
        item_name: 'Coca-Cola (Large)',
        unit_price: 18000,
        quantity: 1,
        subtotal: 18000,
      },
    ],
    food_subtotal: 60500,
    shipping_share: 5000,
    grand_total: 65500,
    payment_status: 'payment_reported',
    status: 'submitted',
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'order-citra',
    session_id: 'session-friday-lunch',
    member_id: 'member-citra',
    member_name: 'Citra',
    items: [
      {
        id: 'oi-5',
        order_id: 'order-citra',
        snapshot_item_id: 'snap-mcd-item-2',
        item_name: 'McChicken',
        unit_price: 38000,
        quantity: 1,
        subtotal: 38000,
      },
      {
        id: 'oi-6',
        order_id: 'order-citra',
        snapshot_item_id: 'snap-mcd-item-8',
        item_name: 'McFlurry Oreo',
        unit_price: 16500,
        quantity: 1,
        subtotal: 16500,
      },
    ],
    food_subtotal: 54500,
    shipping_share: 5000,
    grand_total: 59500,
    payment_status: 'unpaid',
    status: 'submitted',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'order-dani',
    session_id: 'session-friday-lunch',
    member_id: 'member-dani',
    member_name: 'Dani',
    items: [
      {
        id: 'oi-7',
        order_id: 'order-dani',
        snapshot_item_id: 'snap-mcd-item-3',
        item_name: 'Double Cheeseburger',
        unit_price: 42000,
        quantity: 1,
        subtotal: 42000,
      },
    ],
    food_subtotal: 42000,
    shipping_share: 5000,
    grand_total: 47000,
    payment_status: 'paid',
    status: 'submitted',
    created_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
